--1
SELECT c.NOMBRE , p.NOMBRE FROM CLIENTES c, PUEBLOS p
WHERE c.CODPUE =p.CODPUE;
--2
SELECT p.NOMBRE , p2.NOMBRE  FROM PUEBLOS p,PROVINCIAS p2
WHERE p.CODPRO =p2.CODPRO;
--3
SELECT c.NOMBRE , p.NOMBRE , p2.NOMBRE  FROM PUEBLOS p,PROVINCIAS p2,CLIENTES c
WHERE p.CODPRO =p2.CODPRO AND c.CODPUE =p.CODPUE;
--4
SELECT distinct p2.NOMBRE  FROM CLIENTES c, PUEBLOS p, PROVINCIAS p2
WHERE c.CODPUE =p.CODPUE AND p.CODPRO =p2.CODPRO;
--5
SELECT DISTINCT a.DESCRIP FROM LINEAS_FAC lf,ARTICULOS a 
WHERE lf.CODART =a.CODART AND CANT >10;
--6
SELECT f.FECHA , lf.CODART,lf.CANT FROM FACTURAS f , LINEAS_FAC lf
WHERE f.CODFAC = lf.CODFAC
ORDER BY f.FECHA DESC,lf.CODART DESC ,lf.CANT desc;
--7
SELECT f.CODFAC , f.FECHA  FROM FACTURAS f ,CLIENTES c 
WHERE f.CODCLI =c.CODCLI AND c.CODPOSTAL LIKE '%7%';
--8
SELECT f.CODFAC , f.FECHA,c.NOMBRE  FROM FACTURAS f ,CLIENTES c 
WHERE f.CODCLI =c.CODCLI;
--9 se pone tambien si el iva es 0
SELECT distinct f.CODFAC , f.FECHA , f.IVA , f.DTO ,c.NOMBRE FROM FACTURAS f,CLIENTES c
WHERE f.CODCLI =c.CODCLI AND (IVA IS NULL OR iva=0 )OR dto IS NULL;
--10
SELECT DISTINCT a.DESCRIP , a.PRECIO , lf.PRECIO AS precio_menor FROM ARTICULOS a, LINEAS_FAC lf 
WHERE a.CODART = lf.CODART AND lf.PRECIO < a.PRECIO;
--11
SELECT f.CODFAC ,f.FECHA ,nvl(f.IVA,0) ,nvl(f.DTO,0) ,a.DESCRIP ,lf.PRECIO ,lf.CANT ,nvl(lf.DTO,0)  FROM FACTURAS f ,LINEAS_FAC lf , ARTICULOS a
WHERE f.CODFAC = lf.CODFAC AND lf.CODART =a.CODART;
--12
SELECT f.CODFAC ,f.FECHA ,nvl(f.IVA,0) ,nvl(f.DTO,0) ,a.DESCRIP ,lf.PRECIO ,lf.CANT ,nvl(lf.DTO,0) , c.NOMBRE  FROM CLIENTES c ,FACTURAS f ,LINEAS_FAC lf , ARTICULOS a
WHERE c.CODCLI =f.CODCLI AND f.CODFAC = lf.CODFAC AND lf.CODART =a.CODART;
--13
SELECT c.NOMBRE FROM CLIENTES c, PUEBLOS p,PROVINCIAS p2
WHERE c.CODPUE =p.CODPUE AND p.CODPRO = p2.CODPRO 
AND upper(p2.NOMBRE) LIKE '%MA%';
--14 siempre que me salga un dato númerico le pongo el nvl
SELECT f.CODCLI FROM FACTURAS f, LINEAS_FAC lf, ARTICULOS a
WHERE f.CODFAC = lf.CODFAC AND lf.CODART = a.CODART 
AND nvl(a.STOCK,0) < nvl(a.STOCK_MIN,0) ;
--15
SELECT DISTINCT a.DESCRIP FROM ARTICULOS a, LINEAS_FAC lf
WHERE a.CODART =lf.CODART;
--16
SELECT DISTINCT a.DESCRIP , nvl((lf.PRECIO-(lf.DTO*lf.PRECIO /100),0)) AS precioReal FROM ARTICULOS a , LINEAS_FAC lf
WHERE a.CODART = lf.CODART ;
--17
SELECT DISTINCT a.DESCRIP  FROM ARTICULOS a, LINEAS_FAC lf, FACTURAS f, CLIENTES c, PUEBLOS p, PROVINCIAS p2
WHERE a.CODART = lf.CODART 
AND lf.CODFAC =f.CODFAC 
AND f.CODCLI =c.CODCLI 
AND c.CODPUE =p.CODPUE 
AND p.CODPRO =p2.CODPRO 
AND p2.NOMBRE LIKE '%A'; 
--18
SELECT DISTINCT c.NOMBRE FROM CLIENTES c , FACTURAS f
WHERE c.CODCLI =f.CODCLI AND f.DTO >10;
--19
SELECT DISTINCT c.NOMBRE FROM CLIENTES c , FACTURAS f,LINEAS_FAC lf
WHERE c.CODCLI =f.CODCLI AND f.CODFAC =lf.CODFAC 
AND (f.DTO >10 OR lf.LINEA>10) OR (f.DTO >10 AND lf.LINEA>10);
--20
SELECT a.DESCRIP , lf.CANT , lf.PRECIO FROM CLIENTES c, FACTURAS f , LINEAS_FAC lf , ARTICULOS a
WHERE c.CODCLI =f.CODCLI 
AND f.CODFAC = lf.CODFAC 
AND lf.CODART = a.CODART 
AND UPPER(c.NOMBRE) LIKE '%MARIA MERCEDES%';
