--1
SELECT AVG(dto) FROM FACTURAS f;
--2
SELECT AVG(dto) FROM FACTURAS f WHERE f.DTO IS NOT NULL;
--3
SELECT TRUNC(AVG(NVL(dto,0))) FROM FACTURAS f;
--4
SELECT count(CODFAC) FROM FACTURAS f;
--5
SELECT COUNT(p.CODPUE)
FROM PUEBLOS p 
WHERE p.CODPRO IN (3,12,46);
--6
SELECT SUM(a.PRECIO*a.STOCK) FROM ARTICULOS a;
--7
SELECT  count(DISTINCT CODPUE) FROM CLIENTES c 
WHERE c.CODPOSTAL LIKE '12%';
--8
SELECT max(STOCK),min(STOCK),max(STOCK)-min(STOCK) AS diferencia FROM ARTICULOS a
WHERE PRECIO BETWEEN 9 AND 12;
--9
SELECT AVG(nvl(precio,0)) FROM ARTICULOS a
WHERE STOCK >10;
--10
SELECT min(fecha),max(fecha) FROM FACTURAS f 
WHERE CODCLI =210;
--11
SELECT count (codart) FROM ARTICULOS a 
WHERE stock IS NULL;
--12
SELECT trunc(count (linea),1) FROM LINEAS_FAC lf
WHERE dto IS NULL;
--13 dudoso 
SELECT count (codfac) ,f.CODCLI  FROM FACTURAS f
GROUP BY  f.CODCLI; 
--14
SELECT count (codfac),f.CODCLI  FROM FACTURAS f , CLIENTES c
WHERE f.CODCLI =c.CODCLI
GROUP BY f.CODCLI
HAVING count (codfac)>=2; 
--15
SELECT sum(cant*precio) FROM LINEAS_FAC lf;
--16
SELECT sum(lf.cant*lf.precio) FROM LINEAS_FAC lf,ARTICULOS a 
WHERE lf.CODART =a.CODART AND UPPER(a.CODART) LIKE '%A%';
--17
SELECT count(codfac),fecha FROM facturas
GROUP BY fecha;
--18
SELECT count(c.CODCLI),p.NOMBRE FROM CLIENTES c, PUEBLOS p
WHERE c.CODPUE =p.CODPUE
GROUP BY p.NOMBRE
ORDER BY count(c.CODCLI) desc;
--19 
--la estructura es select, from ,where, group by , having, order by
SELECT count(c.CODCLI),p.NOMBRE FROM CLIENTES c, PUEBLOS p
WHERE c.CODPUE =p.CODPUE
GROUP BY p.NOMBRE
HAVING count(c.CODCLI) >2
ORDER BY count(c.CODCLI) DESC;
--20
SELECT sum(lf.cant),a.DESCRIP FROM ARTICULOS a,LINEAS_FAC lf
WHERE a.CODART LIKE 'P%'
GROUP BY a.DESCRIP;
--21
SELECT max(precio),min(precio) FROM LINEAS_FAC lf
WHERE CODART LIKE 'C%';
--22
SELECT max(precio),min(precio),max(precio)-min(precio) AS DIFERENCIA FROM LINEAS_FAC lf
WHERE CODART LIKE 'C%';
--23
SELECT a.DESCRIP FROM LINEAS_FAC lf , ARTICULOS a
WHERE lf.CODART =a.CODART
GROUP BY a.DESCRIP 
HAVING sum(lf.precio)>1000;
--24
SELECT DISTINCT count(codfac),codcli,nvl(iva,0) FROM FACTURAS f
WHERE CODCLI BETWEEN 150 AND 300
GROUP BY codcli,iva;
--25
SELECT avg(precio) FROM LINEAS_FAC lf;