CREATE OR REPLACE TRIGGER insertaControl
AFTER INSERT ON empleados
FOR EACH ROW 
BEGIN 
	INSERT INTO CONTROLCAMBIOS VALUES (USER,SYSDATE,'INSERT', NULL,:NEW.DNI);
END;
DELETE FROM EMPLEADOS e WHERE NOMEMP IS NULL;
INSERT INTO EMPLEADOS (DNI,NOMEMP) VALUES('4567','JU');
--Para comprobar que se quede
SELECT * FROM CONTROLCAMBIOS c ;